language: bash
services: docker
before_script:
  - docker -v
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - docker build -t "realpage/dredd:ci" .
  - docker run --rm realpage/dredd:ci dredd --version
  - docker images
after_success:
  # build and push all variations of images
  - if [[ $TRAVIS_PULL_REQUEST_BRANCH == '' && $TRAVIS_BRANCH == 'master' ]]; then bash build.sh ; fi
notifications:
  slack:
    secure: ${SLACK_TOKEN}
